const API_BASE_URL = 'https://localhost:';

export const environment = {
    production: false,
    name: 'Local',
    API_BASE_URL_ALARMS : API_BASE_URL + '2443/',
    API_BASE_URL_ASSETS : API_BASE_URL + '7004/',
    API_BASE_URL_CARRIERS : API_BASE_URL + '5443/',
    API_BASE_URL_BASE : API_BASE_URL + '6443/',
    API_BASE_URL_CUSTOMERACCOUNTS : API_BASE_URL + '7443/',
    API_BASE_URL_DEVICEMANAGEMENT : API_BASE_URL + '9443/',
    API_BASE_URL_INVENTORY : API_BASE_URL + '8443/',
    API_BASE_URL_OEM : API_BASE_URL + '10443/',
    API_BASE_URL_REPORTS : API_BASE_URL + '11443/',
    API_BASE_URL_SERVICEACCOUNTS : API_BASE_URL + '13443/',
    API_BASE_URL_SIM : API_BASE_URL + '14443/',
    API_BASE_URL_USERMANAGEMENT : API_BASE_URL + '15443/',
    API_BASE_URL_SSO : API_BASE_URL + '7079/',
    CLIENT_CODE: 'BackOfficeUI'
};
